#!/usr/bin/env python3
"""Write the licence texts of every Rust crate built into the control panel.

The crates' licences (MIT, Apache-2.0, BSD, Zlib, ...) allow redistribution on
the condition that their notices travel with the binary. The packaging
scripts call this and ship the result as THIRD-PARTY-LICENSES.txt.

    packaging/third-party-licenses.py <output file>

Needs "cargo" and the crate sources (present after "cargo build").
"""
import hashlib
import json
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PATTERNS = ("licen", "copying", "notice", "unlicense", "ofl", "ufl")


SKIP_DIRS = {"src", "tests", "benches", "examples", "target", ".git", ".github"}


def licence_files(directory: pathlib.Path):
    """Licence files in the crate root and one folder below (fonts/, LICENSES/, ...)."""
    files = []
    folders = [directory] + sorted(
        d for d in directory.iterdir() if d.is_dir() and d.name not in SKIP_DIRS
    )
    for folder in folders:
        for path in sorted(folder.iterdir()):
            name = path.name.lower()
            if path.is_file() and (name.startswith(PATTERNS) or "license" in name or "licence" in name) \
                    and not name.endswith((".rs", ".toml", ".py", ".sh")):
                files.append(path)
    return files


MIT = """Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE."""

BSL = """Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE."""


def main(output: str) -> None:
    metadata = json.loads(subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked",
         "--manifest-path", str(ROOT / "panel" / "Cargo.toml")],
        check=True, capture_output=True, text=True).stdout)
    used = {node["id"] for node in metadata["resolve"]["nodes"]}
    crates = sorted(
        (p for p in metadata["packages"] if p["id"] in used and p["name"] != "lamppost-control"),
        key=lambda p: (p["name"], p["version"]),
    )

    seen = {}          # text hash -> crate that printed it first
    apache_texts = []
    out = []
    out.append("Third-party licences of the LAMPPost control panel\n")
    out.append("=" * 52 + "\n\n")
    out.append(f"The lamppost-control binary contains {len(crates)} Rust crates. Their\n")
    out.append("licence notices follow. Where a crate offers a choice of licences, LAMPPost\n")
    out.append("uses it under the permissive option (MIT or Apache-2.0).\n")
    missing = []
    for crate in crates:
        label = f"{crate['name']} {crate['version']}"
        licence = crate.get("license") or crate.get("license_file") or "unknown"
        out.append("\n" + "-" * 78 + "\n")
        out.append(f"{label}\nLicence: {licence}\n")
        if crate.get("authors"):
            out.append(f"Authors: {', '.join(crate['authors'])}\n")
        if crate.get("repository"):
            out.append(f"Source:  {crate['repository']}\n")
        files = licence_files(pathlib.Path(crate["manifest_path"]).parent)
        if not files:
            missing.append(label)
            out.append("(No licence file in the crate: the standard text of the licence named\n"
                       " above applies, printed at the end of this file; copyright holders are\n"
                       " the authors listed.)\n")
        for path in files:
            text = path.read_text(errors="replace").strip()
            digest = hashlib.sha256(text.encode()).hexdigest()
            if digest in seen:
                out.append(f"\n[{path.name}: same text as printed for {seen[digest]}]\n")
                continue
            seen[digest] = label
            if "apache" in path.name.lower():
                apache_texts.append(text)
            out.append(f"\n[{path.relative_to(pathlib.Path(crate['manifest_path']).parent)}]\n{text}\n")

    # the standard texts for crates that only name their licence
    out.append("\n" + "=" * 78 + "\n")
    out.append("Standard licence texts\n")
    out.append("=" * 78 + "\n")
    out.append("\nMIT License (Copyright (c) the authors listed for each crate)\n\n" + MIT + "\n")
    apache = next((text for text in apache_texts if "Apache License" in text and "Version 2.0" in text), None)
    if apache:
        out.append("\nApache License 2.0\n\n" + apache + "\n")
    out.append("\n" + BSL + "\n")

    pathlib.Path(output).write_text("".join(out))
    print(f"{output}: {len(crates)} crates, {len(seen)} distinct licence texts"
          + (f", {len(missing)} without a licence file" if missing else ""))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "THIRD-PARTY-LICENSES.txt")
